// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://figxavvmvnjldkzcscaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpZ3hhdnZtdm5qbGRremNzY2FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTMxNDksImV4cCI6MjA2NTQ4OTE0OX0.6zMZVGZYFJXXRZzXMd76VLO_vhUtZA4k7AfDaH7Z_x0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});